### ISSUE TITLE
superagent 1.1.0 vs 3.8.2

### ISSUE THREAD

**Issue by stcsaba** [jonkemp/remote-content#1]
Changing the superagent dependency is breaking our application (running on node 0.12), as the main version of this package was not changed. We are using inline-css, which depends on extract-css, href-content and at the end remote-content.
Please revert the superagent to 1.1.0 in the v1.x.x versions.

**Comment by jonkemp** [comment]
Node v0.12 reached end of life at the end of 2016 and is no longer supported. If you can't upgrade Node, my suggestion is to fix the version of this package to 1.0.1.

**Comment by stcsaba** [comment]
We cannot downgrade your package, as the dependency is in a package which is a dependency of an other package... 
I am asking you to fix your versioning according to semver.
I know that node v0.12 is not supported, and our upgrade is ongoing, but until then we cannot deploy our app.

**Comment by jonkemp** [comment]
I would argue that I am not violating semver because there were no breaking changes in this module. Tests are passing for all currently supported versions of node. 

This dependency is four levels deep so I would have to bump the major version for four modules to do what you are asking, all with no breaking code changes so that you can stay on a version of node that has not been supported in over a year. My apologies but I am not currently inclined to do that.

You can fork the modules and have npm pull from your repo and then you should be able to deploy.

**Comment by stcsaba** [comment]
You are right in that we are using an outdated node version. 
For quick fix we use npm-shrinkwrap.json.
Thanks.
